# Generated by Django 4.1.2 on 2022-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_lyrics_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(auto_now_add=True),
        ),
    ]
